version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: Docker/Dockerfile
        depends_on:
            - mysql
        ports:
            - 8080:8080
        links:
            - mysql
        environment:
            SPRING_PROFILES_ACTIVE: mysql
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql/petclinic

    
    mysql:
        image: mysql:5.7
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_USER=petclinic
          - MYSQL_PASSWORD=petclinic
          - MYSQL_DATABASE=petclinic