apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  ports:
  - port: 8080
    protocol: TCP
    name: "web"
  - port: 9010
    protocol: TCP
    name: "jmx"
  selector:
    app: petclinic
  type: NodePort